name: Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Ensure themes and submodules are included

      - uses: actions/setup-node@v3
        with:
          node-version: 18  # Set up Node.js (needed for PostCSS, if used)

      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - run: hugo --baseURL "https://dansonmaina.github.io/dansonPortfolio/"

      - run: ls -la public  # Debugging step to check the generated files

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages  # Ensure deployment to the correct branch
